#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
#  - GITEA__mailer__ENABLED=true
#       - GITEA__mailer__FROM=${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
#       - GITEA__mailer__PROTOCOL=smtps
#       - GITEA__mailer__SMTP_ADDR=${GITEA__mailer__SMTP_ADDR:?GITEA__mailer__SMTP_ADDR not set}
#       - GITEA__mailer__SMTP_PORT=${GITEA__mailer__SMTP_PORT:?GITEA__mailer__SMTP_PORT not set}
#       - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
#       - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
#This is specific to you module, so you need to change it accordingly.
HOST = data.get('host')

# Emails
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']
SMTP_ENCRYPTION = smtp_settings['encrypt_smtp']
SMTP_ENABLED='true' if smtp_settings['enabled'] else 'false'

gitea = {
    "LOCAL_ROOT_URL": f'https://{HOST}',
    "GITEA__mailer__ENABLED": SMTP_ENABLED,
    "GITEA__mailer__FROM": SMTP_USERNAME,
    "GITEA__mailer__PROTOCOL": "smtps",
    "GITEA__mailer__SMTP_ADDR": SMTP_HOST,
    "GITEA__mailer__SMTP_PORT": SMTP_PORT,
    "GITEA__mailer__USER": SMTP_USERNAME,
    "GITEA__mailer__PASSWD": SMTP_PASSWORD,
}
agent.write_envfile("gitea.env", gitea)
#agent.dump_env()
